<a href="https://colab.research.google.com/github/somas1/CT/blob/main/Numpy/Copy_of_Data_Science_Day_1_Exercises_Day1_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [1]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]



#convert given lists to NDArrays
nd_height = np.array(height)
nd_weight = np.array(weight)

bmis = nd_weight/(nd_height**2) * 730
zipped_bmis = list(zip(nd_height, nd_weight, bmis))
#print(zipped_bmis)

for entry in range(len(zipped_bmis)):
  print('A height of {} and a weight of {} yields a bmi of {}'.format(zipped_bmis[entry][0],
                                                                      zipped_bmis[entry][1],
                                                                      zipped_bmis[entry][2]))


A height of 69 and a weight of 110 yields a bmi of 16.866204578869986
A height of 70 and a weight of 120 yields a bmi of 17.877551020408163
A height of 71 and a weight of 130 yields a bmi of 18.825629835350128
A height of 72 and a weight of 140 yields a bmi of 19.714506172839506
A height of 73 and a weight of 150 yields a bmi of 20.54794520547945
A height of 74 and a weight of 160 yields a bmi of 21.329437545653764
A height of 75 and a weight of 170 yields a bmi of 22.06222222222222


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [2]:
def random_matrix(x, y, shape=(3,3), kind='int64'):
  '''
  enter the x and y values you would like for a matrix.
  optionally, indicate the shape of the matrix or the data type.
  '''
  return np.random.uniform(x, y, shape).astype(kind)

print(random_matrix(1,55,(3,3)))
print(random_matrix(3,9, (5,5), 'float64'))
print(random_matrix(2,5))

[[15 45 46]
 [18 41 29]
 [47 44  6]]
[[5.81115695 4.26598877 7.243521   5.62141541 4.2679078 ]
 [5.06553171 5.96755112 6.32734621 6.69307431 8.78620103]
 [7.85563107 8.19694613 6.5585216  7.64241099 8.68703614]
 [6.40164501 7.11088189 5.95836984 4.06663275 3.74119226]
 [4.77745247 7.61870511 6.96542165 8.8298893  6.57546266]]
[[2 3 4]
 [2 3 3]
 [3 2 3]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [3]:
import csv
import numpy as np




In [39]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS',
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
def load_data(filename, d = ','):
    data = np.genfromtxt(filename,delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24),invalid_raise=False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('redsox_2017_hitting.txt')
bs2018 = load_data('redsox_2018_hitting.txt')

print(FIELDS)
print(bs2017)
players2017 = [name.decode('utf-8') for name in bs2017['Name']]
players2018 = [name.decode('utf-8') for name in bs2018['Name']]
zipped2017 = list(zip(players2017, bs2017['SLG']))
zipped2018 = list(zip(players2018, bs2018['SLG']))
print(zipped2017)
print(zipped2018)

['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']
[( 1, b'C', b'Christian Vazquez', 26,  99, 345, 324,  43,  94, 18, 2,  5,  32,  7, 2, 17,  64, 0.29 , 0.33 , 0.404, 0.735,  91, 131, 14)
 ( 2, b'1B', b'Mitch Moreland', 31, 149, 576, 508,  73, 125, 34, 0, 22,  79,  0, 1, 57, 120, 0.246, 0.326, 0.443, 0.769,  99, 225, 14)
 ( 3, b'2B', b'Dustin Pedroia', 33, 105, 463, 406,  46, 119, 19, 0,  7,  62,  4, 3, 49,  48, 0.293, 0.369, 0.392, 0.76 , 100, 159, 11)
 ( 4, b'SS', b'Xander Bogaerts', 24, 148, 635, 571,  94, 156, 32, 6, 10,  62, 15, 1, 56, 116, 0.273, 0.343, 0.403, 0.746,  95, 230, 17)
 ( 5, b'3B', b'Rafael Devers', 20,  58, 240, 222,  34,  63, 14, 0, 10,  30,  3, 1, 18,  57, 0.284, 0.338, 0.482, 0.819, 111, 107,  5)
 ( 6, b'LF', b'Andrew Benintendi', 22, 151, 658, 573,  84, 155, 26, 1, 20,  90, 20, 5, 70, 112, 0.271, 0.352, 0.424, 0.776, 102, 243, 16)
 ( 7, 